In [160]:
import  numpy as np

In [161]:
# نوشتن وزن ها علامت ها و اعدادی که باید به ان تقسیم شود
sign_number = [400,10,10,10,10]
sign = ["-","+","+","+","+",]
weight = np.array([[0.83,0.97,1],[0.7,0.9,1],[0.57,0.77,0.93],[0.5,0.7,0.9],[0.7,0.9,1]],dtype=float)

In [162]:
# ماتریس اصلی
matrix = np.array([
    [[700],[6.3,8,9],[5.7,7.7,9],[7,9,10],[3,5,7]],
    [[400],[6,10,10],[7,9,10],[7,9,10],[5,7,9]],
    [[500],[7,9,10],[7,9,10],[8,9,10],[7,9,10]]
],dtype="object")

In [169]:
normal_matrix1=[]
for index,row in enumerate(matrix):
#    print(row[:,index].astype(float)/sign[index])
    for idx,col in enumerate(row):
        if sign[idx]=="+":
          res = np.array(col, dtype=np.float32)/sign_number[idx]
        
        else: res = sign_number[idx]/np.array(col, dtype=np.float32)
#         print(res)
        normal_matrix1.append(res)
#     print("---------")
#     print(normal_matrix)

In [171]:
#ماتریس نرمال
normal_matrix =np.reshape(np.asarray(normal_matrix1, dtype=object),matrix.shape)
normal_matrix

array([[array([0.5714286], dtype=float32),
        array([0.63, 0.8 , 0.9 ], dtype=float32),
        array([0.57, 0.77, 0.9 ], dtype=float32),
        array([0.7, 0.9, 1. ], dtype=float32),
        array([0.3, 0.5, 0.7], dtype=float32)],
       [array([1.], dtype=float32),
        array([0.6, 1. , 1. ], dtype=float32),
        array([0.7, 0.9, 1. ], dtype=float32),
        array([0.7, 0.9, 1. ], dtype=float32),
        array([0.5, 0.7, 0.9], dtype=float32)],
       [array([0.8], dtype=float32),
        array([0.7, 0.9, 1. ], dtype=float32),
        array([0.7, 0.9, 1. ], dtype=float32),
        array([0.8, 0.9, 1. ], dtype=float32),
        array([0.7, 0.9, 1. ], dtype=float32)]], dtype=object)

In [172]:
w_matrix = []
for nrow in normal_matrix:
    for index,col in enumerate(nrow):
        res = col*weight[index]
        w_matrix.append(res)

In [175]:
# ضرب ماتریس نرمال در وزن ها 
w_matrix=np.reshape(np.asarray(w_matrix, dtype=float),(3,5,3))
w_matrix

array([[[0.47428574, 0.55428574, 0.5714286 ],
        [0.441     , 0.72000001, 0.89999998],
        [0.3249    , 0.59289999, 0.83699998],
        [0.34999999, 0.62999998, 0.9       ],
        [0.21000001, 0.45      , 0.69999999]],

       [[0.83      , 0.97      , 1.        ],
        [0.42000002, 0.9       , 1.        ],
        [0.39899999, 0.69299998, 0.93      ],
        [0.34999999, 0.62999998, 0.9       ],
        [0.35      , 0.62999999, 0.89999998]],

       [[0.66400001, 0.77600001, 0.80000001],
        [0.48999999, 0.80999998, 1.        ],
        [0.39899999, 0.69299998, 0.93      ],
        [0.40000001, 0.62999998, 0.9       ],
        [0.48999999, 0.80999998, 1.        ]]])

In [176]:
# جمع ردیف ها با یکدیگر
sum_row = [sum(row) for row in w_matrix ]
sum_row

[array([1.80018573, 2.94718572, 3.90842854]),
 array([2.349     , 3.82299995, 4.72999998]),
 array([2.44299999, 3.71899993, 4.63000001])]

In [183]:
# تابع روش مساحت 
def fuzzy_p(pa,pb):
    print(pa[0]-pb[2],pa[1]-pb[1],pa[2]-pb[0])

In [181]:
fuzzy_p(sum_row[0],sum_row[2])

-2.829814281463623 -0.7718142151832574 1.4654285466670989
