#FASW

In [2]:
import  numpy as np

In [17]:
# نوشتن وزن ها علامت ها و اعدادی که باید به ان تقسیم شود
sign_number = [10,10,10,10,5]
sign = ["+","+","+","+","-"]
weight = np.array([[0.7,0.9,1],[0.7,0.8,0.9],[0.6,0.7,0.8],[0.8,0.9,1],[0.5,0.7,0.9]],dtype=float)

In [18]:
# ماتریس اصلی
matrix = np.array([
    [[6,7,8],[7,9,10],[6,7,9],[4,6,8],[5,7,8]],
    [[6,8,10],[5,6,8],[4,5,8],[6,9,10],[6,7,8]],
    [[5,7,8],[6,7,9],[8,9,10],[6,7,8],[6,8,10]]
],dtype="object")

In [19]:
normal_matrix1=[]
for index,row in enumerate(matrix):
#    print(row[:,index].astype(float)/sign[index])
    for idx,col in enumerate(row):
        if sign[idx]=="+":
          res = np.array(col, dtype=np.float32)/sign_number[idx]
        
        else: res = sign_number[idx]/np.array(col, dtype=np.float32)
#         print(res)
        normal_matrix1.append(res)
#     print("---------")
#     print(normal_matrix)

In [20]:
#ماتریس نرمال
normal_matrix =np.reshape(np.asarray(normal_matrix1, dtype=object),matrix.shape)
normal_matrix

array([[[0.6000000238418579, 0.699999988079071, 0.800000011920929],
        [0.699999988079071, 0.8999999761581421, 1.0],
        [0.6000000238418579, 0.699999988079071, 0.8999999761581421],
        [0.4000000059604645, 0.6000000238418579, 0.800000011920929],
        [1.0, 0.7142857313156128, 0.625]],

       [[0.6000000238418579, 0.800000011920929, 1.0],
        [0.5, 0.6000000238418579, 0.800000011920929],
        [0.4000000059604645, 0.5, 0.800000011920929],
        [0.6000000238418579, 0.8999999761581421, 1.0],
        [0.8333333134651184, 0.7142857313156128, 0.625]],

       [[0.5, 0.699999988079071, 0.800000011920929],
        [0.6000000238418579, 0.699999988079071, 0.8999999761581421],
        [0.800000011920929, 0.8999999761581421, 1.0],
        [0.6000000238418579, 0.699999988079071, 0.800000011920929],
        [0.8333333134651184, 0.625, 0.5]]], dtype=object)

In [21]:
w_matrix = []
for nrow in normal_matrix:
    for index,col in enumerate(nrow):
        res = col*weight[index]
        w_matrix.append(res)

In [22]:
# ضرب ماتریس نرمال در وزن ها 
w_matrix=np.reshape(np.asarray(w_matrix, dtype=float),(3,5,3))
w_matrix

array([[[0.42000002, 0.62999999, 0.80000001],
        [0.48999999, 0.71999998, 0.9       ],
        [0.36000001, 0.48999999, 0.71999998],
        [0.32      , 0.54000002, 0.80000001],
        [0.5       , 0.50000001, 0.5625    ]],

       [[0.42000002, 0.72000001, 1.        ],
        [0.35      , 0.48000002, 0.72000001],
        [0.24      , 0.35      , 0.64000001],
        [0.48000002, 0.80999998, 1.        ],
        [0.41666666, 0.50000001, 0.5625    ]],

       [[0.35      , 0.62999999, 0.80000001],
        [0.42000002, 0.55999999, 0.80999998],
        [0.48000001, 0.62999998, 0.8       ],
        [0.48000002, 0.62999999, 0.80000001],
        [0.41666666, 0.4375    , 0.45      ]]])

In [23]:
# جمع ردیف ها با یکدیگر
# جمع کردن سطحی 
sum_row = [sum(row) for row in w_matrix ]
sum_row

[array([2.09000003, 2.88      , 3.7825    ]),
 array([1.9066667 , 2.86000002, 3.92250002]),
 array([2.1466667 , 2.88749995, 3.66      ])]

In [24]:
# تابع روش مساحت 
def fuzzy_p(pa,pb):
    print(pa[0]-pb[2],pa[1]-pb[1],pa[2]-pb[0])

In [25]:
fuzzy_p(sum_row[0],sum_row[2])

-1.5699999749660498 -0.007499957084655673 1.6358333051204683


In [26]:
fuzzy_p(sum_row[0],sum_row[1])

-1.8324999928474428 0.01999997496604866 1.875833308696747


In [27]:
fuzzy_p(sum_row[1],sum_row[2])

-1.7533333063125616 -0.027499932050704334 1.775833320617676
