In [34]:
import  numpy as np
import math

In [20]:
# نوشتن وزن ها علامت ها و اعدادی که باید به ان تقسیم شود
sign_number = [2.5,2700,21000,4.5,1,1]
sign = ["+","+","+","-","+","+"]
weight = np.array([[0.6,0.675,0.75],[0.4,0.5,0.6],[0.4,0.5,0.6],[0.4,0.5,0.6],[0.75,0.825,0.9],[0.9,0.95,1]],dtype=float)

In [21]:
matrix = np.array([
    [[2],[1500],[20000],[5.5],[0.3,0.5,0.7],[0.9,0.95,1]],
    [[2.5],[2700],[18000],[6.5],[0.1,0.2,0.3],[0.2,0.5,0.7]],
    [[1.8],[2000],[21000],[4.5],[0.7,0.8,0.9],[0.7,0.8,9]],
    [[2.2],[1800],[20000],[5.0],[0.3,0.5,0.7],[0.3,0.5,0.7]],
],dtype="object")


In [22]:
normal_matrix1=[]
for index,row in enumerate(matrix):
    for idx,col in enumerate(row):
        if sign[idx]=="+":
          res = np.array(col, dtype=np.float32)/sign_number[idx]
        
        else: res = sign_number[idx]/np.array(col, dtype=np.float32)
#         print(res)
        normal_matrix1.append(res)
#     print("---------")
#     print(normal_matrix)

In [41]:
# ماتریس R
# ماتریس نرمال شده 
normal_matrix =np.reshape(np.asarray(normal_matrix1, dtype=object),matrix.shape)
print(normal_matrix)

[[array([0.8], dtype=float32) array([0.5555556], dtype=float32)
  array([0.95238096], dtype=float32) array([0.8181818], dtype=float32)
  array([0.3, 0.5, 0.7], dtype=float32)
  array([0.9 , 0.95, 1.  ], dtype=float32)]
 [array([1.], dtype=float32) array([1.], dtype=float32)
  array([0.85714287], dtype=float32) array([0.6923077], dtype=float32)
  array([0.1, 0.2, 0.3], dtype=float32)
  array([0.2, 0.5, 0.7], dtype=float32)]
 [array([0.71999997], dtype=float32) array([0.7407407], dtype=float32)
  array([1.], dtype=float32) array([1.], dtype=float32)
  array([0.7, 0.8, 0.9], dtype=float32)
  array([0.7, 0.8, 9. ], dtype=float32)]
 [array([0.88], dtype=float32) array([0.6666667], dtype=float32)
  array([0.95238096], dtype=float32) array([0.9], dtype=float32)
  array([0.3, 0.5, 0.7], dtype=float32)
  array([0.3, 0.5, 0.7], dtype=float32)]]


In [24]:
w_matrix = []
for nrow in normal_matrix:
    for index,col in enumerate(nrow):
        res = col*weight[index]
        w_matrix.append(res)

In [31]:
# ماتریس v
# ماتریس نرمال شده ضرب در ماتریس وزن ها
w_matrix=np.reshape(np.asarray(w_matrix, dtype=float),(4,6,3))
w_matrix

array([[[0.48000001, 0.54000001, 0.60000001],
        [0.22222223, 0.27777779, 0.33333335],
        [0.38095238, 0.47619048, 0.57142857],
        [0.32727273, 0.40909091, 0.49090909],
        [0.22500001, 0.4125    , 0.62999999],
        [0.80999998, 0.90249999, 1.        ]],

       [[0.6       , 0.675     , 0.75      ],
        [0.4       , 0.5       , 0.6       ],
        [0.34285715, 0.42857143, 0.51428572],
        [0.27692308, 0.34615386, 0.41538463],
        [0.075     , 0.165     , 0.27000001],
        [0.18      , 0.475     , 0.69999999]],

       [[0.43199998, 0.48599998, 0.53999998],
        [0.29629629, 0.37037036, 0.44444443],
        [0.4       , 0.5       , 0.6       ],
        [0.4       , 0.5       , 0.6       ],
        [0.52499999, 0.66000001, 0.80999998],
        [0.62999999, 0.76000001, 9.        ]],

       [[0.528     , 0.594     , 0.66      ],
        [0.26666667, 0.33333334, 0.40000001],
        [0.38095238, 0.47619048, 0.57142857],
        [0.35999999, 0.44999

In [39]:
def distance(a,b):
    res = math.sqrt((1/3*(((a[0]-b[0])**2)+((a[1]-b[1])**2)+((a[2]-b[2])**2))))
    print(res)
    

In [42]:
distance([0.43199998, 0.48599998, 0.53999998],[0.48000001, 0.54000001, 0.60000001])

0.054221796724203984
