# محاسبه تاپسیس فازی

In [3]:
import  numpy as np
import math

In [4]:
# نوشتن وزن ها علامت ها و اعدادی که باید به ان تقسیم شود
# منظور از 
division_number = [10,10,10,10]
sign = ["+","+","+","+"]
weight = np.array([[0.8,0.9,1],[0.7,0.8,0.9],[0.8,0.9,1],[0.7,0.8,1]],dtype=float)

In [8]:
#  ماتریس صورت مسئله
matrix = np.array([
    [[7,9,10],[6,7,9],[4,6,8],[5,7,8]],
    [[5,6,8],[4,5,8],[6,9,10],[6,7,8]],
    [[6,7,9],[8,9,10],[6,7,8],[6,8,10]],
],dtype="float")


In [9]:
# فرایند نرمال سازی ماتریس
normal_matrix1=[]
for index,row in enumerate(matrix):
    for idx,col in enumerate(row):
        if sign[idx]=="+":
          res = np.array(col, dtype=np.float32)/division_number[idx]
        
        else: res = division_number[idx]/np.array(col, dtype=np.float32)
#         print(res)
        normal_matrix1.append(res)
#     print("---------")
#     print(normal_matrix)

In [11]:
# ماتریس R
# ماتریس نرمال شده 
normal_matrix =np.reshape(np.asarray(normal_matrix1, dtype=float),matrix.shape)
print(normal_matrix)

[[[0.69999999 0.89999998 1.        ]
  [0.60000002 0.69999999 0.89999998]
  [0.40000001 0.60000002 0.80000001]
  [0.5        0.69999999 0.80000001]]

 [[0.5        0.60000002 0.80000001]
  [0.40000001 0.5        0.80000001]
  [0.60000002 0.89999998 1.        ]
  [0.60000002 0.69999999 0.80000001]]

 [[0.60000002 0.69999999 0.89999998]
  [0.80000001 0.89999998 1.        ]
  [0.60000002 0.69999999 0.80000001]
  [0.60000002 0.80000001 1.        ]]]


In [12]:
w_matrix = []
for nrow in normal_matrix:
    for index,col in enumerate(nrow):
        res = col*weight[index]
        w_matrix.append(res)

In [15]:
# ماتریس v
# ماتریس نرمال شده ضرب در ماتریس وزن ها
# ماتریس موزون
w_matrix=np.reshape(np.asarray(w_matrix, dtype=float),(3,4,3))
w_matrix

array([[[0.55999999, 0.80999998, 1.        ],
        [0.42000002, 0.55999999, 0.80999998],
        [0.32      , 0.54000002, 0.80000001],
        [0.35      , 0.55999999, 0.80000001]],

       [[0.4       , 0.54000002, 0.80000001],
        [0.28      , 0.4       , 0.72000001],
        [0.48000002, 0.80999998, 1.        ],
        [0.42000002, 0.55999999, 0.80000001]],

       [[0.48000002, 0.62999999, 0.89999998],
        [0.56000001, 0.71999998, 0.9       ],
        [0.48000002, 0.62999999, 0.80000001],
        [0.42000002, 0.64000001, 1.        ]]])

In [16]:
# ایده ال مثبت
# find max col in above matrix
positve_ideal = [
    [0.55999999, 0.80999998, 1.        ],
    [0.56000001, 0.71999998, 0.9       ],
    [0.48000002, 0.80999998, 1.        ],
    [0.42000002, 0.64000001, 1.        ]
]

In [18]:
# ایده ال منفی
# find min col in above matrix
negetive_ideal = [
    [0.4       , 0.54000002, 0.80000001],
    [0.28      , 0.4       , 0.72000001],
    [0.32      , 0.54000002, 0.80000001],
    [0.35      , 0.55999999, 0.80000001],

]

In [19]:
def distance(a,b):
    res = math.sqrt(
        (1/3*
                       (
                           pow((a[0]-b[0]),2)
                          +pow((a[1]-b[1]),2)
                          +pow((a[2]-b[2]),2)
                       )
        )
                   )
    return res
    

In [20]:
for rowIndex,row in enumerate(w_matrix) :
    sum_positve_ideal = float(0)
    sum_negetive_ideal = float(0)
    for idx,col in enumerate(row) : 
        sum_positve_ideal += distance(col,positve_ideal[idx])
        sum_negetive_ideal += distance(col,negetive_ideal[idx])
        
    C_distance = (sum_negetive_ideal/(sum_negetive_ideal+sum_positve_ideal))
    print('d',rowIndex+1,':')
    print("مقدار ایده ال مثبت :",sum_positve_ideal )
    print('مقدار ایده ال منفی :',sum_negetive_ideal)
    print("محاسبه دوری",C_distance)
    print('----------------')
        
    
   

d 1 :
مقدار ایده ال مثبت : 0.47892291009614146
مقدار ایده ال منفی : 0.3481559347515995
محاسبه دوری 0.42094648765401854
----------------
d 2 :
مقدار ایده ال مثبت : 0.6058126394822346
مقدار ایده ال منفی : 0.25527881484253523
محاسبه دوری 0.29645958458932065
----------------
d 3 :
مقدار ایده ال مثبت : 0.28288990255411456
مقدار ایده ال منفی : 0.5937072994107708
محاسبه دوری 0.6772863272663668
----------------


In [21]:
distance([0.48, 0.54, 0.6],[0.6,0.675,0.75])

0.1355544171172596
